// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRequestSummary = "request_summary"

// RequestSummary mapped from table <request_summary>
type RequestSummary struct {
	ID         int32     `gorm:"column:id;type:INTEGER" json:"id"`
	IP         string    `gorm:"column:ip;type:TEXT" json:"ip"`
	ReqNum     int32     `gorm:"column:req_num;type:INTEGER" json:"req_num"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName RequestSummary's table name
func (*RequestSummary) TableName() string {
	return TableNameRequestSummary
}
