port: 8559

mysqls:
  - env: prod    
    db: xxl-job
    enable: true
    host: localhost:3306
    user: root
    password: 123456
    
  - env: prod    
    db: smart-ad
    enable: true
    host: localhost:3306
    user: root
    password: 123456

  - env: test
    db: cmswing
    enable: false
    host: localhost:3306
    user: root
    password: 123456
