mode: "dev"
port: 8559

log:
  level: "debug"
  filename: "./log/logfile.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

sqlite:
  path: "../dev-utils.db"

mysql:
  host: localhost
  port: 3306
  user: root
  password: root
  db: library
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
