mode: "prod"
port: 8559

job:
  enable: false
  alive_check: "*/15 * * * * *"

# 钉钉消息
ding_talk:
  enable: false
  url: ***
  alert_duration: 2 # 单位: 分钟
  next_duration: 60 # 单位: 分钟 第一次发送消息后, 每个n分钟再次发消息.

nacos_service:
  list:
    - wimoor-auth: 1
    - wimoor-admin: 1
    - wimoor-amazon: 2
    - wimoor-gateway: 1
    - wimoor-erp: 1
    - wimoor-amazon-adv: 2



log:
  level: "debug"
  filename: "./log/logfile.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

sqlite:
  path: "../dev-utils.db"

mysqls:
  - env: 本地测试
    host: localhost
    port: 3306
    user: root
    password: 123456
    db: gin-bili
    max_open_conns: 100
    max_idle_conns: 20

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
