// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAlertJob = "alert_job"

// AlertJob mapped from table <alert_job>
type AlertJob struct {
	ID            int32     `gorm:"column:id;type:INTEGER" json:"id"`
	AppName       string    `gorm:"column:app_name;type:TEXT" json:"app_name"`
	Type          string    `gorm:"column:type;type:TEXT" json:"type"`
	HTTPMethod    string    `gorm:"column:http_method;type:TEXT" json:"http_method"`
	URL           string    `gorm:"column:url;type:TEXT" json:"url"`
	Head          string    `gorm:"column:head;type:TEXT" json:"head"`
	Body          string    `gorm:"column:body;type:TEXT" json:"body"`
	Owner         string    `gorm:"column:owner;type:TEXT" json:"owner"`
	Phone         string    `gorm:"column:phone;type:TEXT" json:"phone"`
	LastExeResult int32     `gorm:"column:last_exe_result;type:INTEGER" json:"last_exe_result"`
	LastFailTime  time.Time `gorm:"column:last_fail_time;type:datetime" json:"last_fail_time"`
	HeathState    int32     `gorm:"column:heath_state;type:INTEGER" json:"heath_state"`
	State         int32     `gorm:"column:state;type:INTEGER" json:"state"`
	Note          string    `gorm:"column:note;type:TEXT" json:"note"`
	CreateTime    time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime    time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName AlertJob's table name
func (*AlertJob) TableName() string {
	return TableNameAlertJob
}
