// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAlertLog = "alert_log"

// AlertLog mapped from table <alert_log>
type AlertLog struct {
	ID          int32     `gorm:"column:id;type:INTEGER" json:"id"`
	AlertJobsID int32     `gorm:"column:alert_jobs_id;type:INTEGER" json:"alert_jobs_id"`
	Result      int32     `gorm:"column:result;type:INTEGER" json:"result"`
	CostTime    int32     `gorm:"column:cost_time;type:INTEGER" json:"cost_time"`
	CreateTime  time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName AlertLog's table name
func (*AlertLog) TableName() string {
	return TableNameAlertLog
}
