// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInterfaceConfig = "interface_config"

// InterfaceConfig mapped from table <interface_config>
type InterfaceConfig struct {
	ID         int32     `gorm:"column:id;type:INTEGER" json:"id"`
	AppName    string    `gorm:"column:app_name;type:TEXT" json:"app_name"`
	Type       string    `gorm:"column:type;type:TEXT" json:"type"`
	HTTPMethod string    `gorm:"column:http_method;type:TEXT" json:"http_method"`
	URL        string    `gorm:"column:url;type:TEXT" json:"url"`
	Owner      string    `gorm:"column:owner;type:TEXT" json:"owner"`
	Phone      string    `gorm:"column:phone;type:TEXT" json:"phone"`
	FailNum    int32     `gorm:"column:fail_num;type:INTEGER" json:"fail_num"`
	CallNum    int32     `gorm:"column:call_num;type:INTEGER" json:"call_num"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName InterfaceConfig's table name
func (*InterfaceConfig) TableName() string {
	return TableNameInterfaceConfig
}
