// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInterfaceCallLog = "interface_call_log"

// InterfaceCallLog mapped from table <interface_call_log>
type InterfaceCallLog struct {
	ID                int32     `gorm:"column:id;type:INTEGER" json:"id"`
	InterfaceConfigID int32     `gorm:"column:interface_config_id;type:INTEGER" json:"interface_config_id"`
	Result            int32     `gorm:"column:result;type:INTEGER" json:"result"`
	CostTime          int32     `gorm:"column:cost_time;type:INTEGER" json:"cost_time"`
	CreateTime        time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime        time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName InterfaceCallLog's table name
func (*InterfaceCallLog) TableName() string {
	return TableNameInterfaceCallLog
}
