// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRequestLog = "request_log"

// RequestLog mapped from table <request_log>
type RequestLog struct {
	ID         int32     `gorm:"column:id;type:INTEGER" json:"id"`
	IP         string    `gorm:"column:ip;type:TEXT" json:"ip"`
	Plateform  string    `gorm:"column:plateform;type:TEXT" json:"plateform"`
	Path       string    `gorm:"column:path;type:TEXT" json:"path"`
	Event      string    `gorm:"column:event;type:TEXT" json:"event"`
	Params     string    `gorm:"column:params;type:TEXT" json:"params"`
	ReqDay     string    `gorm:"column:req_day;type:TEXT" json:"req_day"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName RequestLog's table name
func (*RequestLog) TableName() string {
	return TableNameRequestLog
}
